name: localsend_app
description: An open source cross-platform alternative to AirDrop

publish_to: 'none'

version: 1.6.2+24

environment:
  sdk: '>=2.18.5 <3.0.0'

dependencies:
  basic_utils: 5.4.2
  collection: 1.16.0
  connectivity_plus: 3.0.2
  desktop_drop: 0.4.0
  device_info_plus: 8.0.0
  dio: 4.0.6
  file_picker: 5.2.4
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_markdown: 0.6.13
  flutter_riverpod: 2.1.3
  freezed_annotation: 2.2.0
  image_gallery_saver: 1.7.1
  image_picker: 0.8.6
  intl: 0.17.0
  json_annotation: 4.7.0
  launch_at_startup: 0.2.1
  network_info_plus: 3.0.1
  open_filex: 4.3.2
  package_info_plus: 3.0.2
  path_provider: 2.0.11
  permission_handler: 10.2.0
  routerino: 0.3.0
  screen_retriever: 0.1.6
  share_handler: 0.0.16
  shared_preferences: 2.0.15
  shelf: 1.4.0
  shelf_router: 1.1.3
  slang: 3.11.1
  slang_flutter: 3.11.0
  tray_manager:
    # https://github.com/leanflutter/tray_manager/issues/30
    # The Linux tray manager is disabled for now
    git:
      url: https://github.com/Tienisto/tray_manager.git
      ref: b37f5e088e0f02c45a684ae41e9d2da2d5c596db
  url_launcher: 6.1.7
  uuid: 3.0.7
  wakelock: 0.6.2
  wechat_assets_picker: 8.3.0
  window_manager: 0.2.8

dev_dependencies:
  build_runner: 2.3.3
  flutter_gen_runner: 5.1.0+1
  flutter_lints: 2.0.1
  freezed: 2.3.2
  json_serializable: 6.5.4
  msix:
    # https://github.com/YehudaKremer/msix/pull/174
    git:
      url: https://github.com/Tienisto/msix.git
      ref: 207eddfe797225ab2736001cbdb8fafd04946b38
  slang_build_runner: 3.11.0
  test: 1.22.1

dependency_overrides:
  share_handler_platform_interface:
    # https://github.com/ShoutSocial/share_handler/pull/39
    # Remove this when next release is published
    git:
      url: https://github.com/ShoutSocial/share_handler.git
      path: share_handler_platform_interface
      ref: 630cf945524dfbae1bc63ed83b28559b47b25ffa

flutter:
  uses-material-design: true

  assets:
    - assets/img/
    - assets/CHANGELOG.md

msix_config:
  display_name: LocalSend
  publisher_display_name: Tien Do Nam
  publisher: CN=0A8E9755-183F-4F0B-823F-1B8C991D7B97
  identity_name: 11157TienDoNam.LocalSend
  logo_path: assets\img\logo-512.png
  languages: en, ar, de, es-ES, fr-FR, hu, in, it, iw, ja, ko, ne, pl, pt-BR, ru, sv, tr, zh-Hans, zh-Hant-HK, zh-Hant-TW
  startup_task:
    task_id: localsend
    enabled: false
    parameters: autostart
