name: localsend_app
description: An open source cross-platform alternative to AirDrop
homepage: https://localsend.org/
publish_to: "none"

version: 1.10.0+32

environment:
  flutter: '>=3.10.5'
  sdk: ">=3.0.5 <4.0.0"

dependencies:
  basic_utils: 5.5.4
  collection: 1.17.1
  connectivity_plus: 3.0.6
  desktop_drop: 0.4.1
  device_apps: 2.2.0
  device_info_plus: 8.2.2
  dio: 5.1.2
  dynamic_color: 1.6.5
  file_picker: 5.2.9
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_markdown: 0.6.14
  flutter_riverpod: 2.3.6
  freezed_annotation: 2.2.0
  image_gallery_saver: 2.0.2
  image_picker: 0.8.9
  intl: 0.18.0
  json_annotation: 4.8.1
  launch_at_startup: 0.2.2
  logging: 1.1.1
  mime: 1.0.4
  network_info_plus: 3.0.5
  open_filex: 4.3.2
  package_info_plus: 3.1.2
  path: 1.8.3
  path_provider: 2.0.14
  permission_handler: 10.2.0
  pretty_qr_code: 2.0.3
  routerino: 0.5.0
  screen_retriever: 0.1.6
  share_handler: 0.0.16
  shared_preferences: 2.1.1
  shared_storage: 0.7.1
  shelf: 1.4.1
  shelf_router: 1.1.4
  slang: 3.19.0
  slang_flutter: 3.19.0
  system_settings: 2.1.0
  system_tray: 2.0.3
  tray_manager:
    # https://github.com/leanflutter/tray_manager/issues/30
    # The Linux tray manager is disabled for now
    git:
      url: https://github.com/Tienisto/tray_manager.git
      ref: b37f5e088e0f02c45a684ae41e9d2da2d5c596db
  url_launcher: 6.1.11
  uuid: 3.0.7
  wakelock: 0.6.2
  wechat_assets_picker: 8.5.0
  window_manager: 0.3.2

dev_dependencies:
  build_runner: 2.4.5
  custom_lint: 0.3.4
  flutter_gen_runner: 5.3.1
  flutter_lints: 2.0.1
  freezed: 2.3.3
  json_serializable: 6.6.2
  msix: 3.14.2
  riverpod_lint: 1.3.1
  slang_build_runner: 3.19.0
  test: any

dependency_overrides:
  permission_handler_windows:
    # Remove windows support as it causes trouble with Windows 7
    # https://github.com/Baseflow/flutter-permission-handler/issues/1034
    git:
      url: https://github.com/localsend/permission_handler_windows_noop.git
      ref: fc09b707ab4535a9214c87b16f09feda7e765d90
  share_handler_platform_interface:
    # https://github.com/ShoutSocial/share_handler/pull/39
    # Remove this when next release is published
    git:
      url: https://github.com/ShoutSocial/share_handler.git
      path: share_handler_platform_interface
      ref: 630cf945524dfbae1bc63ed83b28559b47b25ffa

flutter:
  uses-material-design: true

  assets:
    - assets/img/
    - assets/web/
    - assets/CHANGELOG.md

msix_config:
  display_name: LocalSend
  publisher_display_name: Tien Do Nam
  # Using third-party CA for now (see: https://github.com/localsend/localsend/issues/220)
  # publisher: CN=0A8E9755-183F-4F0B-823F-1B8C991D7B97
  identity_name: 11157TienDoNam.LocalSend
  logo_path: assets\img\logo-512.png
  languages: en, ar, bn, cs, de, es-ES, fa, fr-FR, hu, in, it, iw, ja, ko, ne, nl, pl, pt-BR, ru, sv, tr, uk, zh-Hans, zh-Hant-HK, zh-Hant-TW

  # https://github.com/localsend/localsend/issues/398
  os_min_version: 10.0.19041.0

  startup_task:
    task_id: localsend
    enabled: false
    parameters: autostart
