name: cli
description: A sample command-line application.
version: 1.0.0
publish_to: "none"

environment:
  sdk: ^3.1.1

dependencies:
  args: 2.4.2
  common:
    path: ../common
  path: 1.9.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
