name: cli
description: A sample command-line application.
version: 1.0.0
publish_to: "none"

environment:
  sdk: ^3.1.1

dependencies:
  common:
    path: ../common

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
