name: localsend_app
description: An open source cross-platform alternative to AirDrop
homepage: https://localsend.org/
publish_to: "none"

version: 1.17.0+58

environment:
  flutter: ^3.25.0
  sdk: ^3.9.0

dependencies:
  basic_utils: 5.7.0
  bitsdojo_window: ^0.1.6
  collection: ^1.17.2 # allow newer versions, so it can compile with newer Flutter versions
  common:
    path: ../common
  connectivity_plus: 6.1.0
  convert: 3.1.2
  dart_mappable: 4.6.0
  desktop_drop: 0.5.0
  device_apps: 2.2.0
  device_info_plus: 11.1.1
  dynamic_color: 1.8.1
  file_picker: 8.1.4
  file_selector: 1.0.3
  flutter:
    sdk: flutter
  flutter_displaymode: 0.6.0
  flutter_localizations:
    sdk: flutter
  flutter_markdown: 0.7.4+2
  flutter_rust_bridge: 2.11.1
  freezed_annotation: 3.1.0
  gal: 2.3.0
  glob: ^2.1.2
  image: 4.5.4
  image_picker: 1.1.2
  in_app_purchase: 3.2.0 # [FOSS_REMOVE]
  intl: ^0.20.2 # allow newer versions, so it can compile with newer Flutter versions
  legalize: 1.2.2
  local_hero: 0.3.0
  logging: 1.3.0
  # https://github.com/NightFeather0615/macos_dock_progress/issues/1
  # macos_dock_progress: 1.1.0
  mime: 1.0.6
  moform: 0.2.5
  nanoid2: 2.0.1
  network_info_plus: 6.1.1
  open_dir: 0.0.2+1
  open_filex: 4.7.0
  package_info_plus: 8.1.1
  pasteboard: 0.3.0
  path: 1.9.1
  path_provider: 2.1.5
  path_provider_foundation: 2.4.0
  permission_handler: 11.3.1
  pretty_qr_code: 3.3.0
  refena_flutter: 3.1.0
  refena_inspector_client: 2.1.0
  rhttp: 0.13.0
  routerino: 0.8.0
  rust_lib_localsend_app:
    path: rust_builder
  saf_stream: 0.10.0
  screen_retriever: 0.2.0
  share_handler: 0.0.22
  shared_preferences: 2.5.2
  shared_preferences_platform_interface: any
  slang: 4.9.0
  slang_flutter: 4.9.0
  system_settings_2: 3.0.1
  tray_manager: 0.2.4
  uri_content: 3.1.1
  url_launcher: 6.3.1
  uuid: 4.5.1
  wakelock_plus: 1.2.8
  wechat_assets_picker: 9.8.0
  win32_registry: 1.1.5
  window_manager: 0.5.1
  windows_taskbar: 1.1.2
  yaru: 8.3.0

dev_dependencies:
  build_runner: 2.7.1
  dart_mappable_builder: 4.6.0
  flutter_gen_runner: 5.12.0
  flutter_lints: 5.0.0
  freezed: 3.2.3
  mockito: 5.5.0
  refena_inspector: 2.1.0
  slang_build_runner: 4.9.0
  test: ^1.26.2

dependency_overrides:
  device_apps:
    # Migrate to another maintained package to fetch installed apps on Android
    git:
      url: https://github.com/Tienisto/device_apps.git
      ref: 5dc7956d938541254d2e175766b3b84ea38bb85b
  pasteboard:
    # This is temporary workaround, wait upstream for update
    git:
      url: https://github.com/Seidko/flutter-plugins.git
      ref: 58748dae405df5e68a131e4905d48e75d0624be2
      path: packages/pasteboard
  permission_handler_windows:
    # Remove windows support as it causes trouble with Windows 7
    # https://github.com/Baseflow/flutter-permission-handler/issues/1034
    git:
      url: https://github.com/localsend/permission_handler_windows_noop.git
      ref: 2dadd8afbf81e0e3e4791d7144e689555e58f649

flutter:
  uses-material-design: true

  assets:
    - assets/img/
    - assets/web/
    - assets/CHANGELOG.md

flutter_gen:
  line_length: 150
