name: common
description: Common code used by the app and by the cli.
version: 1.0.0
publish_to: "none"

environment:
  sdk: ^3.5.0

dependencies:
  collection: ^1.17.2 # allow newer versions, so it can compile with newer Flutter versions
  dart_mappable: ^4.2.0
  logging: ^1.2.0
  meta: ^1.9.1
  mime: ^1.0.4
  refena: ^3.1.0

dev_dependencies:
  build_runner: ^2.4.7
  dart_mappable_builder: ^4.2.0
  lints: ^2.0.0
  test: ^1.21.0
